### ISSUE TITLE
Isochrone not started ?

### ISSUE THREAD

**Issue by zakot** [CanalTP/navitia-docker-compose#19]
When i run navitia explorer linked to local navitia docker compose , I have this message when trying isochrone :
"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. You have requested this URI [/v1/coverage/default/isochrones] but did you mean ..."

I tried what's here :  https://github.com/CanalTP/navitia/issues/1905            
   
but can't find the file.
can you help me ?
Zakaria.

**Comment by antoine-de** [comment]
you can add the environment variable `JORMUNGANDR_GRAPHICAL_ISOCHRONE=True` to the jormungandr container

**Comment by zakot** [comment]
Ok thank you ,
I did this but still the same message.
Do i have to restart something ?

**Comment by pbougue** [comment]
Yes, you have to restart jormungandr

**Comment by zakot** [comment]
Ok thank you , I manage to make it work by adding the environment variable in the docker-compose.yml file and rebuilding jormungandr.
Zakaria.
