### ISSUE TITLE
Docker Insert New Data

### ISSUE THREAD

**Issue by nikiizvorski** [CanalTP/navitia-docker-compose#23]
Hi just wanted to ask if adding new data to the existing default is possible. Seems doesn't work for me i added all the commands that were needed and it still doesn't accept the new data.Thanks

Example: docker cp data/dumb_ntfs.zip navitiadockercompose_tyr_worker_1:/srv/ed/input/default/

We are adding one of the other datasets to the composition. Other than that works fine. And everything is connected.

**Comment by nikiizvorski** [comment]
Steps Done

1. followed everything that was needed actually on the git
2. Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a9
thats the versions that i am using atm
3. just cp the data in the nativia
4. and after nothing else happens when i check it data doesn't exist

Logs: https://pastebin.com/RHujveWd

**Comment by TeXitoi** [comment]
Fixed, from IRC:
```
13:14 < nikiizvorski> just to let you know it imports the data now
```
