### ISSUE TITLE
Navitia Docker Compose - New Coverage

### ISSUE THREAD

**Issue by nikiizvorski** [CanalTP/navitia-docker-compose#24]
Hey guys just wanted to see if its possible to add a new coverage since atm i tryed everything pretty much and can't seem to make it work. Atm i can only override the current instance.

Kind Regards,
Niki

**Comment by TeXitoi** [comment]
From IRC:
```
15:39 < antoine_1> can't tis work: 
                   https://github.com/CanalTP/navitia-docker-compose#additional-instances
15:39 < antoine_1> ?
```

**Comment by TeXitoi** [comment]
@nikiizvorski Please try to search by yourself before asking us questions. Such trivial questions will bother us and we will not be motivated to answer the future ones.

Interesting read: https://stackoverflow.com/help/how-to-ask

**Comment by nikiizvorski** [comment]
Hey @TeXitoi i did try to do this one to implement this one. Doesn't seem to work for me. Do you have something more that can explain the process?

**Comment by TeXitoi** [comment]
Gives exacly all the commands that you've done, with the logs, why you think it doesn't work, the versions of the software that are installed (at least docker, docker-compose, and any command that you've typed).

It will help us to understand what you've tried. If you've done some simple mistake, we will see it directly in your message. If that's more tricky, we will have a first good vision of what you've done and what you are expecting.

**Comment by nikiizvorski** [comment]
Step 1:

If you need additional instances, you can use the docker-instances.jinja2 to generate another docker-compose file (if you want to do some shiny service discovery instead of this quick and dirty jinja template, we'll hapilly accept the contribution 😉 )

2. you'll need to install j2cli

pip install "j2cli[yaml]"

3. Did check that. You need to provide the list of instances (the easiest way is to give it as a yaml file, check artemis/artemis_instances_list.yml for an example)

4. This one said doesn't exist but it create a file for me j2 docker-instances.jinja2 my_instances_list.yml > additional_navitia_instances.yml

5. Used the commands to start that

Then you need to start the docker-compose with the additional instances

docker-compose -f docker-compose.yml -f additional_navitia_instances.yml up

And didn't start anything for me after since it was empty i added all the instances that were needed inside. Didn't give me output except the it was not found.

Thanks
