### ISSUE TITLE
Docker image with incorrect timezone

### ISSUE THREAD

**Issue by thiphariel** [CanalTP/navitia-docker-compose#29]
The database docker container reflect incorrect timezone (Africa/Abidjan)

Content of `/etc/localtime` of the container : 

```bash
root@xxxxxxxxxx:/# cat /etc/localtime
TZif2UTCTZif2UTC
UTC0
```

And it's not even possible to change it directly in the container with the `cp /usr/share/zoneinfo/Europe/Paris /etc/localetime` command (the file is not updated, but the command not throwing an error)

Have you any idea on how fix this ?

Thanks

**Comment by pbougue** [comment]
Can you share the URL of your call?
Because some endpoints are "UTC" and the time provided are UTC. If you do a /journeys call for example, it should reflect what you have in data.
But /coverage is in UTC. We just output the timezone used for all the datetimes in the response.

**Comment by thiphariel** [comment]
I'm currently in a local build so I can't share you the URL. What I mean is just for "logging" purposes, cause I prefer to have datetime in my locale instead of UTC. 

Here is the `/v1/status`

![image](https://user-images.githubusercontent.com/3125705/42763762-44e4ae0a-8914-11e8-95d5-4eddb440cdbb.png)

**Comment by Darkham42** [comment]
Have you try in the docker-compose.yml to add this where you want to change your timezone : 
`
  environment:
    TZ: "/usr/share/zoneinfo/Europe/Paris"
  command: >
    sh -c $TZ /etc/localtime
`

**Comment by pbougue** [comment]
OK, so getting UTC timezone on `/status` or `/coverage` is on purpose.
The context is the timezone used in the response navitia sends.
And in those endpoints, there is no timezone to be prefered, as informations returned are more server-related than region-related.
If you try a `/journeys` or a `/departures` call, the timezone will again match the datetime used in the response... Which are in local time of the region you request.
You can compare : `https://api.navitia.io/v1/coverage/sandbox/stop_areas/stop_area%3ARAT%3ASA%3AABBES/departures`
with `https://api.navitia.io/v1/status`.

It's like you get the timezone part of the standard datetime, only it's once in the feed, not in every datetime.

And yes, the part of the URL after /v1 is already a good information.

**Comment by thiphariel** [comment]
For example, on Tyr web, when I see a failed job, I want to have `updated_at: xxxxT164050` instead of `updated_at: xxxxT144050`. You'll tell me "ok, if you know this is UTC, just add 2h and you're good to go", yup but i's kinda annoying me 😁

There is no way to pass some extra vars on the `docker_compose yml` file to achieve this ?

**Comment by pbougue** [comment]
So not navitia itself, Tyr (not traveler-information part). Well I don't remember how it is managed, but my guess is we wanted all those stuffs in UTC. Maybe it's following the server timezone, but not sure at all.
And there has been no work on displaying a context on that endpoint and we don't plan much work in the future. If you have any idea and a bit of time, we can offer support on PR on this, though.

**Comment by thiphariel** [comment]
Ok. I'll try to tweak things when I'll have some free time and get back here with feedbacks, but it's not gonna be soon ^^
Thanks !
