### ISSUE TITLE
on compose 2.1 cannot create data

### ISSUE THREAD

**Issue by blackerhot** [CanalTP/navitia-docker-compose#52]
regions": [
    {
      "status": "no_data",
      "dataset_created_at": "",
      "name": null,
      "start_production_date": "",
      "shape": "",
      "end_production_date": "",
      "id": "default"
    }

when do i need to copy data ? while running a server ?
what really des path do i need to copy to ?
it happend " no such directory" when i put " docker cp data/dumb_ntfs.zip navitiadockercompose_tyr_worker_1:/srv/ed/input/default/ "

**Comment by blackerhot** [comment]
i ran on windows 10  desktop with compose 2.1

**Comment by blackerhot** [comment]
i can use cat command , that i put file on container .zip but should i extract file or else ?

**Comment by pbougue** [comment]
Hello,
I don't know how it behaves on windows, not knowing of anyone testing it and it's not planned. But as it's dockerised, it could work.
No file extraction is needed, it's done automatically.

The point is to copy the `data/dumb_ntfs.zip` file from this repository to the given location in the given container.
Then data processing is not immediate, but you should end up with a running coverage.

**Comment by blackerhot** [comment]
thank you for answer.this problem 'cp command' that not compatible on windows 10 docker i also still dont know why it be like this but when i ran it on ubuntu it worked so smooth :D this end
