### ISSUE TITLE
How can i fix this code ?  "code": "dead_socket",  

### ISSUE THREAD

**Issue by blackerhot** [CanalTP/navitia-docker-compose#57]
"status": "dead",
      "shape": null,
      "id": "default",
      "name": null,
      "error": {
        "code": "dead_socket",
        "value": "The region default is dead"

run on windows 10
and try to deploy on rancher k8s same code

**Comment by blackerhot** [comment]
![image](https://user-images.githubusercontent.com/29283963/64047771-eab9f100-cb99-11e9-86f9-d47be5a899f0.png)
i found this about postgis error

**Comment by kinnou02** [comment]
What command did you run?
It looks like your database hasn't started, you should have a container named `navitia_database_1` hosting the postgis database.
Also this error is related to kraken, so it looks like it didn't start either, please post the full log.

I checked the last version, everything sound fine (I didn't load any data):
```
 curl -s http://localhost:9191/v1/coverage/default | jq .regions
[
  {
    "status": "no_data",
    "dataset_created_at": "",
    "name": null,
    "start_production_date": "",
    "shape": "",
    "end_production_date": "",
    "id": "default"
  }
]
```

**Comment by blackerhot** [comment]
try to reinstall docker on windows this help me :D
