### ISSUE TITLE
Unable to start python application — OSError: Error relocating /usr/lib/libgeos_c.so

### ISSUE THREAD

**Issue by nicolaswurtz** [CanalTP/navitia-docker-compose#61]
Hi !

I've tested without result on two differents systems (with up-to-date docker) and same results.

The ending message says `--- no python application found, check your startup logs for errors ---` and when looking at it, `navitia_tyr_beat_1` has exited and I found lots of same error message (including in others containers) : 

```
tyr_beat_1                | OSError: Error relocating /usr/lib/libgeos_c.so.1.11.2: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

Steps to reproduce :
- git clone https://github.com/CanalTP/navitia-docker-compose
- cd navitia-docker-compose
- docker-compose up

Thanx !

**Comment by kinnou02** [comment]
Hi,

We are working on it, but in the meantime you can use the previous version `v2.88.0`  by doing:
```
TAG=v2.88.0 docker-compose up
```
Thanks

**Comment by nicolaswurtz** [comment]
Thank you, perfect working with 2.88 !

**Comment by mbounabi** [comment]
Hello,
new docker images fixing this issue are now available in dockerhub!
