### ISSUE TITLE
kirin to navitia Queue

### ISSUE THREAD

**Issue by alibouaziz** [CanalTP/navitia-docker-compose#77]
can anyone explain to me, what is the queue that kirin send GTFS-RT to navitia.
thanks

**Comment by pbougue** [comment]
For Kirin, you have to declare (http POST) a contributor that's gonna handle GTFS-RT : https://github.com/CanalTP/kirin#post

Then this same `id` is used for rabbitmq to Navitia.

Then navitia's Kraken has to listen to it.
You may get inspiration from artemis' instance that is using it (`realtime.cots` here for a COTS input): https://github.com/CanalTP/navitia-docker-compose/blob/04b1025f1c118d7509cb140ba30531e65a3b0ed2/artemis/docker-artemis-instance.yml#L194

Hope this helps.

**Comment by alibouaziz** [comment]
thank @pbougue 
but i try to eliminate kirin, and send GTFS-RT msg directly to navitia
???

**Comment by pbougue** [comment]
Even though it's close, Navitia (exact component is Kraken) does not get GTFS-RT, it gets an extension of it : https://github.com/CanalTP/chaos-proto/blob/master/kirin.proto

So it ties closely Navitia to Kirin. And this feed they exchange is not considered an interface so far (no mandatory backward-compatibility and so on). Which means we consider OK changing it all, over time (even if there are small technical constraints when changing things for us).

So currently, I advise one who wants to feed GTFS-RT to Navitia to use Kirin (that's exactly its role).

**Comment by pbougue** [comment]
Closing this issue now.
Feel free to reopen it, add details or create a new one on the subject if my response was not enough for your needs (not sure what your exact purpose is :wink: ).
